name: 0 - Run Everything


on:
  workflow_dispatch:
  push:
    branches: [main]
  

jobs:
  test_django:
    uses: ./.github/workflows/hello-world.yaml
  test_django_again:
    needs: test_django
    uses: ./.github/workflows/hello-world.yaml
