name: 0 - Run Everything


on:
  workflow_dispatch:
  push:
    branches: [main]
  

jobs:
  test_django:
    uses: ./.github/workflows/test-django.yaml
    secrets:
      DJANGO_SECRET_KEY: "${{ secrets.DJANGO_SECRET_KEY }}"
  build_django:
    needs: test_django
    uses: ./.github/workflows/container.yaml